include_cols = [
    "retail_and_recreation_percent_change_from_baseline",
    "grocery_and_pharmacy_percent_change_from_baseline",
    "parks_percent_change_from_baseline",
    "transit_stations_percent_change_from_baseline",
    "workplaces_percent_change_from_baseline",
    "residential_percent_change_from_baseline",
    "covidnet",
    "positiveInc",
    "negativeInc",
    "cdc_hospitalized",
    "death_jhu_incidence",
    "dex_a",
    "apple_mobility",
    "fb_survey_cli",
    "fb_survey_wili",
]
